name: MainCmd
main: plugin.maincmd.MainCmd
version: 0.5(Getting along...)
author: immac636 (Ian)
commands:
    maincmd:
        description: Gives a description of this plugin. [help] [#] will show the corresponding help page.
    tp:
        description: Teleport a player to another player
    tphere:
        description: Teleport a player to you
    tpto:
        description: Teleport to a player
    jump:
        description: Jump to where youre looking
    send:
        description: Send a player where youre looking
    spawn:
        description: Send yourself or another player to the spawn
    setspawn:
        description: Set the spawn of your current world to your current location. Disregards direction
    boom:
        description: Boom!
    ping:
        description: Returns "Pong!"
    give:
        description: Gives a player an amount of stuff
    i:
        description: Gives you stuff
    item:
        description: same as i
permissions:
    MainCmd.*:
        description: Gives access to all MainCmd commands.
        children:
            MainCmd.teleport.*: true
            MainCmd.player.*: true
            MainCmd.test.*: true
    MainCmd.teleport.*:
        description: Gives access to all teleport commands.
        children:
            MainCmd.teleport.tp: true
            MainCmd.teleport.tphere: true
            MainCmd.teleport.tpto: true
            MainCmd.teleport.jump: true
            MainCmd.teleport.send: true
            MainCmd.teleport.spawn: true
            MainCmd.teleport.setspawn: true
    MainCmd.player.*:
        description: Gives access to all player commands.
        children:
            MainCmd.player.give: true
            MainCmd.player.item: true
    MainCmd.test.*:
        description: Gives access to all test commands.
        children:
            MainCmd.test.boom: true
            MainCmd.test.boom.others: true
            MainCmd.test.ping: true
    MainCmd.test.boom.*:
        children:
            MainCmd.test.boom: true
            MainCmd.test.boom.others: true
    MainCmd.teleport.tp:
        default: false
    MainCmd.teleport.tphere:
        default: false
    MainCmd.teleport.tpto:
        default: false
    MainCmd.teleport.jump:
        default: false
    MainCmd.teleport.send:
        default: false
    MainCmd.teleport.spawn:
        default: false
    MainCmd.teleport.setspawn:
        default: false
    MainCmd.player.give:
        default: op
    MainCmd.player.item:
        default: op
    MainCmd.test.boom:
        default: op
    MainCmd.test.boom.others:
        default: op
    MainCmd.test.ping:
        default: op