name: MainCmd
main: plugin.maincmd.MainCmd
version: 1.1 (Release!)
author: immac636
commands:
    maincmd:
        description: Gives a description of this plugin. [help] [#] will show the corresponding help page.
    tp:
        description: Teleport a player to another player
    tphere:
        description: Teleport a player to you
    tpto:
        description: Teleport to a player
    jump:
        description: Jump to where youre looking
    send:
        description: Send a player where youre looking
    spawn:
        description: Send yourself or another player to the spawn
    setspawn:
        description: Set the spawn of your current world to your current location. Disregards direction
    boom:
        description: Boom!
    ping:
        description: Returns "Pong!"
    give:
        description: Gives a player an amount of stuff
    i:
        description: Gives you stuff
    item:
        description: same as i
    home:
        description: Teleports you to your home, if its set
    sethome:
        description: Sets your home to your current location.
    warp:
        description: Warp to the specified warp
    setwarp:
        description: Set a warp at your current location.
    rmwarp:
        description: Remove a warp
    removewarp:
        description: Same as rmwarp
    god:
        description: Toggles god on/off
    creative:
        description: Turns on creative
    survival:
        description: turns on survival
    afk:
        description: toggles afk
    heal:
        description: heals yourself
    feed:
        description: feeds yourself
    kick:
        description: kick a player
    ban:
        description: ban a player
    unban:
        description: unban a player
    say:
        description: say something
    dev:
        description: unknown
permissions:
    MainCmd.*:
        description: Gives access to all MainCmd commands.
        children:
            MainCmd.teleport.*: true
            MainCmd.player.*: true
            MainCmd.test.*: true
            MainCmd.admin.*: true
            MainCmd.main.reload: true
            MainCmd.chatcolor: true
    MainCmd.admin.*:
            MainCmd.admin.kick: true
            MainCmd.admin.kick.all: true
            MainCmd.admin.kick.all.safe: true
            MainCmd.admin.ban: true
            MainCmd.admin.unban: true
    MainCmd.teleport.*:
        description: Gives access to all teleport commands.
        children:
            MainCmd.teleport.tp: true
            MainCmd.teleport.tphere: true
            MainCmd.teleport.tpto: true
            MainCmd.teleport.jump: true
            MainCmd.teleport.send: true
            MainCmd.teleport.spawn: true
            MainCmd.teleport.setspawn: true
            MainCmd.teleport.home: true
            MainCmd.teleport.sethome: true
            MainCmd.teleport.warp: true
            MainCmd.teleport.setwarp: true
            MainCmd.teleport.rmwarp: true
    MainCmd.player.*:
        description: Gives access to all player commands.
        children:
            MainCmd.player.give: true
            MainCmd.player.item: true
            MainCmd.player.god: true
            MainCmd.player.god.others: true
            MainCmd.player.creative: true
            MainCmd.player.creative.others: true
            MainCmd.player.survival: true
            MainCmd.player.survival.others: true
            MainCmd.player.afk: true
            MainCmd.player.heal: true
            MainCmd.player.feed: true
    MainCmd.test.*:
        description: Gives access to all test commands.
        children:
            MainCmd.test.boom: true
            MainCmd.test.boom.others: true
            MainCmd.test.ping: true
    MainCmd.test.boom.*:
        children:
            MainCmd.test.boom: true
            MainCmd.test.boom.others: true
    MainCmd.admin.kick:
        default: op
    MainCmd.admin.kick.all:
        default: op
    MainCmd.admin.kick.all.safe:
        default: false
    MainCmd.admin.ban:
        default: op
    MainCmd.admin.unban:
        default: op
    MainCmd.teleport.tp:
        default: false
    MainCmd.teleport.tphere:
        default: false
    MainCmd.teleport.tpto:
        default: false
    MainCmd.teleport.jump:
        default: false
    MainCmd.teleport.send:
        default: false
    MainCmd.teleport.spawn:
        default: false
    MainCmd.teleport.setspawn:
        default: false
    MainCmd.teleport.home:
        default: true
    MainCmd.teleport.sethome:
        default: true
    MainCmd.teleport.warp:
        default: false
    MainCmd.teleport.setwarp:
        default: false
    MainCmd.teleport.rmwarp:
        default: op
    MainCmd.player.give:
        default: op
    MainCmd.player.item:
        default: op
    MainCmd.player.god:
        default: op
    MainCmd.player.god.others:
        default: op
    MainCmd.player.creative:
        default: op
    MainCmd.player.creative.others:
        default: op
    MainCmd.player.survival:
        default: op
    MainCmd.player.survival.others:
        default: op
    MainCmd.player.afk:
        default: true
    MainCmd.player.heal:
        default: op
    MainCmd.player.feed:
        default: op
    MainCmd.test.boom:
        default: op
    MainCmd.test.boom.others:
        default: op
    MainCmd.test.ping:
        default: op
    MainCmd.main.reload:
        default: op
    MainCmd.chatcolor:
        default: false